version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    command: ["--wait-timeout=28800"]
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

nginx:
  container_name: nginx
  image: jonasal/ngnix-certbot
  restart: always
  environment:
    - CERTBOT_EMAIL=name@example.com
  ports:
    - 80:80
    - 443:443
  volumes:
    - ngnix_secrets:/etc/letsencrypt
    - ./user_conf.d:/etc/ngnix/user_conf.d
  depends_on:
    - myportfolio


volumes:
  mydatabase:
  nginx_secrets: